[workspace]
members = ["my-lib", "my-exe"]

[workspace.package]
authors = ["{{authors}}"]
description = "{{description}}"
repository = "https://github.com/{{github-username}}/{{project-name}}"
edition = "2021"
