[placeholders]
description = { type = "string", prompt = "A one-liner package description", default = "Another Rust package" }
github-username = { type = "string", prompt = "GitHub username", default = "sshine" }
